package tcputils

const (
	SERVICEQ_NO_ERR      = 600
	SERVICEQ_FLOODED_ERR = 601
	UPSTREAM_NO_ERR      = 700
	UPSTREAM_TCP_ERR     = 701
	UPSTREAM_HTTP_ERR    = 702

	RESPONSE_FLOODED      = "SERVICEQ_FLOODED"
	RESPONSE_TIMED_OUT    = "UPSTREAM_TIMED_OUT"
	RESPONSE_SERVICE_DOWN = "UPSTREAM_DOWN"
	RESPONSE_NO_RESPONSE  = "UPSTREAM_NO_RESPONSE"
)
